print('Welcome to "SAU"', end="")
print("Welcome to 'DTI'", end="")
print("----------------")
print('Welcome to \'SAU\'')
print("welcome to \"DTI\"")
print("----------------")
print(4546)
print(4547.0545)
print(True)
print(False)
print(15 *10 + 20) #expression นิพจน์ 
print( True or False and False)